// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ougcgxtndwoyxayhusie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91Z2NneHRuZHdveXhheWh1c2llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3ODkxMjEsImV4cCI6MjA2MjM2NTEyMX0.p0oCDRdaymF5OmNqq6WkM1kDaoFDT92gZD56lAthqLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);